In [5]:
import sys

nabPath = "/Users/seeker/TNwork/nabonlineanalysis/nabpyinstallations/pyNab/src"
deltaRicePath = "/Users/seeker/TNwork/nabonlineanalysis/nabpyinstallations/deltarice/build/lib.macosx-11.0-arm64-cpython-312/"

sys.path.append(deltaRicePath)
sys.path.append(nabPath)

import nabPy as Nab

In [6]:
import numpy as np
import pandas as pd

In [7]:
import holoviews as hv
import hvplot.pandas
import glob as gl

In [8]:
files = sorted(gl.glob("../../datafiles/hdf5files/Aug2023/*35*.h5"))
print(files)
file = files[0]
run = Nab.File(file)

['../../datafiles/hdf5files/Aug2023/Run3588_0.h5', '../../datafiles/hdf5files/Aug2023/Run3588_1.h5', '../../datafiles/hdf5files/Aug2023/Run3588_2.h5', '../../datafiles/hdf5files/Aug2023/Run3588_3.h5']


In [9]:
print('There are ', run.singleWaves().numWaves, ' singles waveforms, each is ', run.singleWaves().wavelength, ' long')
print('There are ', run.coincWaves().numWaves, ' coincidence waveforms, each is ', run.coincWaves().wavelength, ' long')
print('There are ', run.pulsrWaves().numWaves, ' pulser waveforms, each is ', run.pulsrWaves().wavelength, ' long')
print('There are ', run.noiseWaves().numWaves, ' noise waveforms, each is ', run.noiseWaves().wavelength, ' long')
print('There are ', run.triggers().numtrigs, ' triggers')

There are  295658  singles waveforms, each is  7000  long
There are  7108  coincidence waveforms, each is  7000  long
There are  0  pulser waveforms, each is  0  long
There are  720  noise waveforms, each is  14000  long
There are  303797  triggers


In [10]:
# hv.Scatter(run.triggers().waves()[0].compute())

In [11]:
# run.plotHitLocations(sourceFile='triggers', det = 'top', plot=True)

In [12]:
pixels = run.singleWaves().headers(True)['pixel']
pixels

0          116
1           13
2         1100
3          107
4           13
          ... 
295653    1038
295654    1110
295655      71
295656      83
295657    1108
Name: pixel, Length: 295658, dtype: int64

In [13]:
singlewaves = run.singleWaves()
headers = singlewaves.headers().query("pixel < 200").index headers.to_numpy()

SyntaxError: invalid syntax (2079688927.py, line 2)

In [14]:
x,y = np.histogram(pixels, bins = 256)
hv.Scatter((y[1:], x))

:Scatter   [x]   (y)

In [15]:
trigs = run.triggers().triggers()
# trigs.head(50)

In [16]:
single = headers.timestamp.to_numpy()
single

NameError: name 'headers' is not defined

In [17]:
bigts = trigs.timestamp.to_numpy()

In [18]:
np.in1d(bigts,single)[:100]

NameError: name 'single' is not defined

In [19]:
single[:20]

NameError: name 'single' is not defined

In [20]:
bigts[20:50]

array([10002085431378, 10002085544264, 10002085567302, 10002085567304,
       10002085567344, 10002085452704, 10002085600008, 10002085671628,
       10002085664674, 10002085756496, 10002085865944, 10002085830162,
       10002085826714, 10002085826732, 10002085996448, 10002086036800,
       10002086036804, 10002086036824, 10002086026370, 10002086220674,
       10002086174668, 10002086171830, 10002086342990, 10002086391438,
       10002086235862, 10002086302158, 10002086339620, 10002086438416,
       10002086499142, 10002086392068], dtype=uint64)

In [21]:
10002085996448 -10002085992948
10002085059284 - 10002085055784 
10002085062770 - 10002085059270

3500

In [67]:
single = run.singleWaves().headers()
coinc = run.coincWaves().headers()
# single['type'] = 'single'
# single['event type'].hist()
# single.head()
# single.append(coinc).head()
type(single)
# single = pd.concat([single, coinc])
single.shape

(295658, 13)

In [68]:
# # run.singleWaves().numWaves
single = single.drop(columns=['result', 'bc', 'req', 'event type', 'hit type', 'blank', 'eventid', 'checksum', 'board', 'channel', 'unix timestamp'])
single['evttype'] = 'single'
coinc = coinc.drop(columns=['result', 'bc', 'req', 'event type', 'hit type', 'blank', 'eventid', 'checksum', 'board', 'channel', 'unix timestamp'])
coinc['evttype'] = 'coinc'
df = pd.concat([single, coinc])
df.head()
# single.head()
# single.pixel.hist()

timestamp  pixel evttype
0  10002084016032    116  single
1  10002085668128     13  single
2  10002085992948   1100  single
3  10002086168330    107  single
4  10002089785026     13  single

In [77]:
avar = 'single'
df.query("evttype == @avar").index

int

In [80]:
a = None
# a = 1
if a:
    print("hh")

In [38]:
aa = run.singleWaves().waves()[2].compute()
len(aa)

7000

In [22]:
single = run.singleWaves().headers(False).timestamp.to_numpy()
chk = bigts[np.where(np.in1d(bigts-3500, single))]
bigts[np.in1d(bigts-3500, single)] = 1
# chk.sum()
chk

array([10002083788358, 10002083841588, 10002083733768, ...,
       10020877016110, 10020877336628, 10020877307072], dtype=uint64)

In [23]:
# run.noiseWaves().headers(False).query("pixel > 200").timestamp.to_numpy()

In [24]:
len(single)

295658

In [25]:
2100/162204

0.01294665976178146

In [82]:
a = np.arange(20)
np.random.choice(a, 5)

array([ 9,  0, 19,  3,  1])

In [26]:
run.singleWaves().waves()[0].compute()

array([-59., -41., -41., ..., -64., -67., -53.], dtype=float32)

In [32]:
run.singleWaves().waves()[0:1].compute()

array([[-59., -41., -41., ..., -64., -67., -53.]], dtype=float32)

In [28]:
run.singleWaves().waves()[1:1].compute()

array([], shape=(0, 7000), dtype=float32)

In [29]:
run.coincWaves().waves()[2].compute()

array([-65., -42., -40., ..., -81., -67., -61.], dtype=float32)

In [30]:
hv.Scatter(np.random.normal(size = 10))
# np.random.normal(10)

:Scatter   [x]   (y)

In [31]:
import numpy as np
np.random.normal(size=(1,3))

array([[1.11713198, 0.27488018, 0.51572581]])